FROM nginxplus
LABEL maintainer="NGINX Plus Docker Maintainers: Prodip K Saha"

RUN rm /etc/nginx/conf.d/default.conf

COPY api-aspnet4you-aks.crt /etc/ssl/certs/api-aspnet4you-aks.crt
COPY api-aspnet4you-aks.key /etc/ssl/certs/api-aspnet4you-aks.key
COPY token-signing-key.jwk  /etc/ssl/certs/token-signing-key.jwk
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
COPY html /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
